[theme]
primaryColor="#27AE60"              # Deep green
backgroundColor="#d8fbe2"          # Mint white
secondaryBackgroundColor="#DCFCE7" # Light green cards
textColor="#14532D"                # Rich dark green
font="sans serif"